PREFIX ex:   <http://example.org/uni/schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?clase (COUNT(?x) AS ?n)
WHERE {
    ?clase a owl:Class .
    ?x a ?clase .
}
GROUP BY ?clase
ORDER BY DESC(?n)