PREFIX ex:   <http://example.org/uni/schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

#SELECT ?estudiante ?curso
#WHERE {
#    ?estudiante ex:cursa ?curso .
#}

SELECT ?estudiante ?seccion ?curso
WHERE {
    ?estudiante ex:inscritoEn ?seccion .
    ?seccion ex:perteneceACurso ?curso .
}

